version: '3.8'

services:
  # 1. მონაცემთა ბაზა
  db:
    image: mysql:8.0
    container_name: serial_tracker_db
    restart: always
    environment:
      MYSQL_DATABASE: serial_tracker
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: tracker_user
      MYSQL_PASSWORD: tracker_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: serial_tracker_backend
    restart: always
    ports:
      - "8443:8443"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: serial_tracker_frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  mysql_data: